## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_database.csv")
vacation_df.head()

City_ID              City Country  Max Temp Current Description      Lat  \
0        1             xinyu      CN     82.42     overcast clouds  27.8043   
1        3   arraial do cabo      BR     80.56           clear sky -22.9661   
2        9  puerto escondido      MX     86.83     overcast clouds  15.8500   
3       10            atuona      PF     77.74    scattered clouds  -9.8000   
4       15          cabedelo      BR     83.07    scattered clouds  -6.9811   

        Lng                     Hotel Name  
0  114.9334              Xinyu Beihu Hotel  
1  -42.0278            Pousada Porto Praia  
2  -97.0667  Aldea del Bazar Hotel and Spa  
3 -139.0333                    Villa Enata  
4  -34.8339              Pousada Camboinha

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=2)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df['City']=='matara')
                                & (vacation_df['Hotel Name']=='Amaloh Boutique Resort')]
vacation_end = vacation_df.loc[(vacation_df['City']=='matara')
                                & (vacation_df['Hotel Name']=='Amaloh Boutique Resort')]
vacation_stop1 = vacation_df.loc[(vacation_df['City']=='hambantota')
                              & (vacation_df['Hotel Name']=='Bungalow 63')]
vacation_stop2 = vacation_df.loc[(vacation_df['City']=='kalmunai')
                              & (vacation_df['Hotel Name']=='VS Villa')]
vacation_stop3 = vacation_df.loc[(vacation_df['City']=='trincomalee')
                                & (vacation_df['Hotel Name']=='Welcombe Hotel')]   

In [32]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = pd.DataFrame(vacation_start[["Lat", "Lng"]]).to_numpy()
end = pd.DataFrame(vacation_end[["Lat", "Lng"]]).to_numpy()
stop1 = pd.DataFrame(vacation_stop1[["Lat", "Lng"]]).to_numpy()
stop2 = pd.DataFrame(vacation_stop2[["Lat", "Lng"]]).to_numpy()
stop3 = pd.DataFrame(vacation_stop3[["Lat", "Lng"]]).to_numpy()
start, end, stop1, stop2, stop3

(array([[ 5.9485, 80.5353]]),
 array([[ 5.9485, 80.5353]]),
 array([[ 6.1241, 81.1185]]),
 array([[ 7.4167, 81.8167]]),
 array([[ 8.5711, 81.2335]]))

In [34]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

# Latitude-longitude pairs
start = (5.9485, 80.5353)
end = (5.9485, 80.5353)
stop1 = (6.1241, 81.1185)
stop2 = (7.4167, 81.8167)
stop3 = (8.5711, 81.2335)

fig = gmaps.figure()
itinerary_plan = gmaps.directions_layer(
    start,end,
    waypoints=[stop1,stop2,stop3],
    travel_mode="DRIVING")
fig.add_layer(itinerary_plan)
fig

Figure(layout=FigureLayout(height='420px'))

In [35]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID         City Country  Max Temp Current Description     Lat  \
0      526       matara      LK     76.06       broken clouds  5.9485   
1      308   hambantota      LK     79.47          light rain  6.1241   
2      291     kalmunai      LK     81.03       broken clouds  7.4167   
3      363  trincomalee      LK     81.28     overcast clouds  8.5711   

       Lng              Hotel Name  
0  80.5353  Amaloh Boutique Resort  
1  81.1185             Bungalow 63  
2  81.8167                VS Villa  
3  81.2335          Welcombe Hotel

In [44]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [45]:
# 11a. Add a marker layer for each city to the map.
itinerary_locations = itinerary_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(7.5, 81.0), zoom_level=7)
marker_layer = gmaps.marker_layer(itinerary_locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))